FROM node:20
WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/ .

# Install wait-for-it
RUN apt-get update && apt-get install -y netcat-openbsd

EXPOSE 5001
CMD ["sh", "-c", "until nc -z db 5432; do echo 'Waiting for Postgres...'; sleep 2; done; node server.js"]
