
services:
  # Database Service
  db:
    image: postgres:15
    container_name: rating_platform_db
    environment:
      POSTGRES_DB: rating_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
       - postgres_data:/var/lib/postgresql/data
       - ./migrations/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rating_platform_backend
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rating_platform
      DB_USER: admin
      DB_PASS: admin123
      JWT_SECRET: your_jwt_secret_key_here
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rating_platform_frontend
    environment:
      REACT_APP_API_URL: http://backend:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge