services:
  db:
    image: postgres:15
    container_name: rating_platform_db
    environment:
      POSTGRES_DB: rating_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rating_platform_backend
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rating_platform
      DB_USER: admin
      DB_PASS: admin123
      JWT_SECRET: your_jwt_secret_key_here
      PORT: 5001
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rating_platform_frontend
    environment:
      REACT_APP_API_URL: http://localhost:5001/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules  # Use named volume for node_modules
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  frontend_node_modules:  # Add this volume

networks:
  app-network:
    driver: bridge